# Generated by Django 6.0.2 on 2026-03-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_blockedip_failedloginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedloginattempt',
            name='ip',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
