# Generated by Django 6.0.2 on 2026-03-31 22:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewInventory',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.inventoryitem')),
            ],
            options={
                'db_table': 'inventory_review',
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
