# Generated by Django 6.0.2 on 2026-04-01 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_reviewinventory'),
        ('product', '0007_usedcriticaltoken'),
    ]

    operations = [
    ]
