# Generated by Django 6.0.2 on 2026-04-01 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='phone',
        ),
    ]
