# Generated by Django 6.0.2 on 2026-04-02 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_supplier_address_remove_supplier_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='supplier',
            field=models.ForeignKey(blank=True, db_column='supplier_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.supplier'),
        ),
    ]
