# Generated by Django 6.0.2 on 2026-04-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_userriskprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='event',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login exitoso'), ('LOGIN_FAILED', 'Login fallido'), ('LOGOUT', 'Logout'), ('SESSION_EXPIRED', 'Sesión expirada'), ('RISK_DETECTED', 'Riesgo detectado'), ('OTP_FAILED', 'OTP fallido'), ('TOKEN_REUSE_ATTACK', 'Reuso de token')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
