# Generated by Django 6.0.2 on 2026-04-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_usersession_last_activity_alter_securitylog_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedip',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockedip',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
