# Generated by Django 6.0.2 on 2026-04-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_blockedip_blocked_until_alter_blockedip_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitylog',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
