# Generated by Django 6.0.2 on 2026-04-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_securitylog_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedloginattempt',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='failedloginattempt',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterUniqueTogether(
            name='failedloginattempt',
            unique_together={('ip', 'username')},
        ),
    ]
